In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import numpy as np

## Sual 1

In [45]:
data = {'apples':[30],
        'bananas':[21]}

df=pd.DataFrame(data)
df

   apples  bananas
0      30       21

In [46]:
data = {'':['2017 Sales', '2018 Sales'],
        'apples':[35,41],
        'bananas':[21,34]}

df=pd.DataFrame(data)
df

               apples  bananas
0  2017 Sales      35       21
1  2018 Sales      41       34

## Sual 2

In [47]:
data =np.array(['4 cups', '1 cup', '2 large', '1 can'])

ser = pd.Series(data, index= ['Flour', 'Milk', 'Eggs', 'Spam'])

result = ser.rename('Dinner')

print(result)

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

## Sual 3

In [2]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')

df

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

## Sual 4

In [49]:
data = {'':['Year 1','year 2'],'Cows':[12,20],'Goats':[22,19]}
df = pd.DataFrame(data)
df

           Cows  Goats
0  Year 1    12     22
1  year 2    20     19

In [50]:
header = ['','Cows','Goats']
data = [['Year 1', 12, 22],['Year 2', 20, 19]]
data = pd.DataFrame(data, columns=header)
df
data.to_csv('animals.csv', index=False)

## Sual 5

In [60]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
desc = df['description']
desc = pd.DataFrame(desc)
desc

                                              description
0       Aromas include tropical fruit, broom, brimston...
1       This is ripe and fruity, a wine that is smooth...
2       Tart and snappy, the flavors of lime flesh and...
3       Pineapple rind, lemon pith and orange blossom ...
4       Much like the regular bottling from 2012, this...
...                                                   ...
129966  Notes of honeysuckle and cantaloupe sweeten th...
129967  Citation is given as much as a decade of bottl...
129968  Well-drained gravel soil gives this wine its c...
129969  A dry style of Pinot Gris, this is crisp with ...
129970  Big, rich and off-dry, this is powered by inte...

[129971 rows x 1 columns]

## Sual 6

In [61]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
desc = pd.DataFrame(desc)
desc.head(1)

                                         description
0  Aromas include tropical fruit, broom, brimston...

## Sual 7

In [62]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
df.head(1)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia

## Sual 8

In [63]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
series_one = pd.Series(df.description)
print(series_one.head(10))

0    Aromas include tropical fruit, broom, brimston...
1    This is ripe and fruity, a wine that is smooth...
2    Tart and snappy, the flavors of lime flesh and...
3    Pineapple rind, lemon pith and orange blossom ...
4    Much like the regular bottling from 2012, this...
5    Blackberry and raspberry aromas show a typical...
6    Here's a bright, informal red that opens with ...
7    This dry and restrained wine offers spice in p...
8    Savory dried thyme notes accent sunnier flavor...
9    This has great depth of flavor with its fresh ...
Name: description, dtype: object

## Sual 9

In [65]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
frame2 = df[['country', 'province','region_1','region_2']]
frame2.iloc[[0,1,10,100]]

      country           province      region_1      region_2
0       Italy  Sicily & Sardinia          Etna           NaN
1    Portugal              Douro           NaN           NaN
10         US         California   Napa Valley          Napa
100        US           New York  Finger Lakes  Finger Lakes

## sual 10

In [66]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
frame3 = df[['country','variety']]
frame3.head(100)

     country                   variety
0      Italy               White Blend
1   Portugal            Portuguese Red
2         US                Pinot Gris
3         US                  Riesling
4         US                Pinot Noir
..       ...                       ...
95    France                     Gamay
96    France                     Gamay
97        US                  Riesling
98     Italy                Sangiovese
99        US  Bordeaux-style Red Blend

[100 rows x 2 columns]

## sual 11

In [67]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
frame3 = df[['country']]
frame3.iloc[0:15]

     country
0      Italy
1   Portugal
2         US
3         US
4         US
5      Spain
6      Italy
7     France
8    Germany
9     France
10        US
11    France
12        US
13     Italy
14        US

## sual 12

In [68]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
frame4 = df[['variety']]
frame4.iloc[10:45]

                variety
10   Cabernet Sauvignon
11       Gewürztraminer
12   Cabernet Sauvignon
13    Nerello Mascalese
14           Chardonnay
15             Riesling
16               Malbec
17               Malbec
18    Tempranillo Blend
19             Meritage
20            Red Blend
21           Pinot Noir
22          White Blend
23               Merlot
24         Nero d'Avola
25           Pinot Noir
26          White Blend
27         Nero d'Avola
28            Red Blend
29         Chenin Blanc
30                Gamay
31            Red Blend
32          White Blend
33            Red Blend
34      Sauvignon Blanc
35           Pinot Noir
36  Viognier-Chardonnay
37   Cabernet Sauvignon
38            Primitivo
39         Nero d'Avola
40           Catarratto
41           Pinot Noir
42                Gamay
43      Sauvignon Blanc
44               Merlot

## sual 13

In [69]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
df.set_index('country', inplace=True)
result = df.loc['Italy']
result

,Unnamed: 0,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
country,,,,,,,,,,,,,
Italy,0,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
Italy,6,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
Italy,13,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
Italy,22,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
Italy,24,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Italy,129929,"This luminous sparkler has a sweet, fruit-forw...",NaN,91,38.0,Veneto,Prosecco Superiore di Cartizze,NaN,NaN,NaN,Col Vetoraz Spumanti NV Prosecco Superiore di...,Prosecco,Col Vetoraz Spumanti
Italy,129943,"A blend of Nero d'Avola and Syrah, this convey...",Adènzia,90,29.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio del Cristo di Campobello 2012 Adènzia R...,Red Blend,Baglio del Cristo di Campobello
Italy,129947,"A blend of 65% Cabernet Sauvignon, 30% Merlot ...",Symposio,90,20.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Feudo Principi di Butera 2012 Symposio Red (Te...,Red Blend,Feudo Principi di Butera
Italy,129961,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
Italy,129962,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

## sual 14

In [81]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
frame4 = df.iloc[:, 1:9]
frame4.iloc[10:46]

,country,description,designation,points,price,province,region_1,region_2
10,US,"Soft, supple plum envelopes an oaky structure ...",Mountain Cuvée,87,19.0,California,Napa Valley,Napa
11,France,"This is a dry wine, very spicy, with a tight, ...",NaN,87,30.0,Alsace,Alsace,NaN
12,US,"Slightly reduced, this wine offers a chalky, t...",NaN,87,34.0,California,Alexander Valley,Sonoma
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN
14,US,Building on 150 years and six generations of w...,NaN,87,12.0,California,Central Coast,Central Coast
15,Germany,Zesty orange peels and apple notes abound in t...,Devon,87,24.0,Mosel,NaN,NaN
16,Argentina,"Baked plum, molasses, balsamic vinegar and che...",Felix,87,30.0,Other,Cafayate,NaN
17,Argentina,Raw black-cherry aromas are direct and simple ...,Winemaker Selection,87,13.0,Mendoza Province,Mendoza,NaN
18,Spain,"Desiccated blackberry, leather, charred wood a...",Vendimia Seleccionada Finca Valdelayegua Singl...,87,28.0,Northern Spain,Ribera del Duero,NaN
19,US,"Red fruit aromas pervade on the nose, with cig...",NaN,87,32.0,Virginia,Virginia,NaN
20,US,Ripe aromas of dark berries mingle with ample ...,Vin de Maison,87,23.0,Virginia,Virginia,NaN
21,US,"A sleek mix of tart berry, stem and herb, alon...",NaN,87,20.0,Oregon,Oregon,Oregon Other
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN
23,US,This wine from the Geneseo district offers aro...,Signature Selection,87,22.0,California,Paso Robles,Central Coast
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN
25,US,Oak and earth intermingle around robust aromas...,King Ridge Vineyard,87,69.0,California,Sonoma Coast,Sonoma
26,Italy,Pretty aromas of yellow flower and stone fruit...,Dalila,87,13.0,Sicily & Sardinia,Terre Siciliane,NaN
27,Italy,"Aromas recall ripe dark berry, toast and a whi...",NaN,87,10.0,Sicily & Sardinia,Terre Siciliane,NaN
28,Italy,"Aromas suggest mature berry, scorched earth, a...",Mascaria Barricato,87,17.0,Sicily & Sardinia,Cerasuolo di Vittoria,NaN
29,US,Clarksburg is becoming a haven for Chenin Blan...,NaN,86,16.0,California,Clarksburg,Central Valley
30,France,Red cherry fruit comes laced with light tannin...,Nouveau,86,NaN,Beaujolais,Beaujolais-Villages,NaN
31,Italy,Merlot and Nero d'Avola form the base for this...,Calanìca Nero d'Avola-Merlot,86,NaN,Sicily & Sardinia,Sicilia,NaN
32,Italy,"Part of the extended Calanìca series, this Gri...",Calanìca Grillo-Viognier,86,NaN,Sicily & Sardinia,Sicilia,NaN
33,US,"Rustic and dry, this has flavors of berries, c...",Puma Springs Vineyard,86,50.0,California,Dry Creek Valley,Sonoma
34,US,"This shows a tart, green gooseberry flavor tha...",NaN,86,20.0,California,Sonoma Valley,Sonoma
35,US,As with many of the Erath 2010 vineyard design...,Hyland,86,50.0,Oregon,McMinnville,Willamette Valley
36,Chile,"White flower, lychee and apple aromas carry th...",Estate,86,15.0,Colchagua Valley,NaN,NaN
37,Italy,This concentrated Cabernet offers aromas of cu...,Missoni,86,21.0,Sicily & Sardinia,Sicilia,NaN
38,Italy,"Inky in color, this wine has plump aromas of r...",I Tratturi,86,11.0,Southern Italy,Puglia,NaN
39,Italy,"Part of the natural wine movement, this wine i...",Purato Made With Organic Grapes,86,12.0,Sicily & Sardinia,Sicilia,NaN
40,Italy,Catarratto is one of Sicily's most widely farm...,NaN,86,17.0,Sicily & Sardinia,Sicilia,NaN
41,US,"A stiff, tannic wine, this slowly opens and br...",NaN,86,22.0,Oregon,Willamette Valley,Willamette Valley
42,France,"This is a festive wine, with soft, ripe fruit ...",Nouveau,86,9.0,Beaujolais,Beaujolais,NaN
43,US,"The clean, brisk mouthfeel gives this slightly...",NaN,86,14.0,California,Paso Robles,Central Coast
44,Chile,A berry aroma comes with cola and herb notes. ...,NaN,86,9.0,Maule Valley,NaN,NaN
45,US,Right out of the starting blocks this is an oa...,#SocialSecret,86,40.0,Virginia,Virginia,NaN

In [83]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
df.loc[10:45, 'country':'region_2']

,country,description,designation,points,price,province,region_1,region_2
10,US,"Soft, supple plum envelopes an oaky structure ...",Mountain Cuvée,87,19.0,California,Napa Valley,Napa
11,France,"This is a dry wine, very spicy, with a tight, ...",NaN,87,30.0,Alsace,Alsace,NaN
12,US,"Slightly reduced, this wine offers a chalky, t...",NaN,87,34.0,California,Alexander Valley,Sonoma
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN
14,US,Building on 150 years and six generations of w...,NaN,87,12.0,California,Central Coast,Central Coast
15,Germany,Zesty orange peels and apple notes abound in t...,Devon,87,24.0,Mosel,NaN,NaN
16,Argentina,"Baked plum, molasses, balsamic vinegar and che...",Felix,87,30.0,Other,Cafayate,NaN
17,Argentina,Raw black-cherry aromas are direct and simple ...,Winemaker Selection,87,13.0,Mendoza Province,Mendoza,NaN
18,Spain,"Desiccated blackberry, leather, charred wood a...",Vendimia Seleccionada Finca Valdelayegua Singl...,87,28.0,Northern Spain,Ribera del Duero,NaN
19,US,"Red fruit aromas pervade on the nose, with cig...",NaN,87,32.0,Virginia,Virginia,NaN
20,US,Ripe aromas of dark berries mingle with ample ...,Vin de Maison,87,23.0,Virginia,Virginia,NaN
21,US,"A sleek mix of tart berry, stem and herb, alon...",NaN,87,20.0,Oregon,Oregon,Oregon Other
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN
23,US,This wine from the Geneseo district offers aro...,Signature Selection,87,22.0,California,Paso Robles,Central Coast
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN
25,US,Oak and earth intermingle around robust aromas...,King Ridge Vineyard,87,69.0,California,Sonoma Coast,Sonoma
26,Italy,Pretty aromas of yellow flower and stone fruit...,Dalila,87,13.0,Sicily & Sardinia,Terre Siciliane,NaN
27,Italy,"Aromas recall ripe dark berry, toast and a whi...",NaN,87,10.0,Sicily & Sardinia,Terre Siciliane,NaN
28,Italy,"Aromas suggest mature berry, scorched earth, a...",Mascaria Barricato,87,17.0,Sicily & Sardinia,Cerasuolo di Vittoria,NaN
29,US,Clarksburg is becoming a haven for Chenin Blan...,NaN,86,16.0,California,Clarksburg,Central Valley
30,France,Red cherry fruit comes laced with light tannin...,Nouveau,86,NaN,Beaujolais,Beaujolais-Villages,NaN
31,Italy,Merlot and Nero d'Avola form the base for this...,Calanìca Nero d'Avola-Merlot,86,NaN,Sicily & Sardinia,Sicilia,NaN
32,Italy,"Part of the extended Calanìca series, this Gri...",Calanìca Grillo-Viognier,86,NaN,Sicily & Sardinia,Sicilia,NaN
33,US,"Rustic and dry, this has flavors of berries, c...",Puma Springs Vineyard,86,50.0,California,Dry Creek Valley,Sonoma
34,US,"This shows a tart, green gooseberry flavor tha...",NaN,86,20.0,California,Sonoma Valley,Sonoma
35,US,As with many of the Erath 2010 vineyard design...,Hyland,86,50.0,Oregon,McMinnville,Willamette Valley
36,Chile,"White flower, lychee and apple aromas carry th...",Estate,86,15.0,Colchagua Valley,NaN,NaN
37,Italy,This concentrated Cabernet offers aromas of cu...,Missoni,86,21.0,Sicily & Sardinia,Sicilia,NaN
38,Italy,"Inky in color, this wine has plump aromas of r...",I Tratturi,86,11.0,Southern Italy,Puglia,NaN
39,Italy,"Part of the natural wine movement, this wine i...",Purato Made With Organic Grapes,86,12.0,Sicily & Sardinia,Sicilia,NaN
40,Italy,Catarratto is one of Sicily's most widely farm...,NaN,86,17.0,Sicily & Sardinia,Sicilia,NaN
41,US,"A stiff, tannic wine, this slowly opens and br...",NaN,86,22.0,Oregon,Willamette Valley,Willamette Valley
42,France,"This is a festive wine, with soft, ripe fruit ...",Nouveau,86,9.0,Beaujolais,Beaujolais,NaN
43,US,"The clean, brisk mouthfeel gives this slightly...",NaN,86,14.0,California,Paso Robles,Central Coast
44,Chile,A berry aroma comes with cola and herb notes. ...,NaN,86,9.0,Maule Valley,NaN,NaN
45,US,Right out of the starting blocks this is an oa...,#SocialSecret,86,40.0,Virginia,Virginia,NaN

## sual 15

In [129]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')

df1 = df.loc[((df['points']>95) & (df['country']=='Australia') | (df['country']=='New Zealand')),['country','winery','points']]
df1

            country                       winery  points
174     New Zealand                   Stoneleigh      88
311     New Zealand        Otto's Constant Dream      87
345       Australia  Chambers Rosewood Vineyards     100
346       Australia  Chambers Rosewood Vineyards      98
348       Australia  Chambers Rosewood Vineyards      97
...             ...                          ...     ...
129953  New Zealand                   Mills Reef      90
129954  New Zealand                          Ara      90
129955  New Zealand                    Dog Point      90
129956  New Zealand                   Esk Valley      90
129958  New Zealand                       Babich      90

[1441 rows x 3 columns]

## sual 16 baxx

In [157]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
df.loc[[1,2,3,5,8]]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
5,5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
8,8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel

## sual 17

In [159]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
df['points'].mean()

88.44713820775404

In [163]:
median = df['points'].median()
median

88.0

In [161]:
df['points'].max()

100

In [162]:
df['points'].min()

80

## sual 18

In [182]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
df2=df.country.unique()
df2= pd.DataFrame(df2)
df2.sort_values(by = 0, ascending = True)

                         0
6                Argentina
36                 Armenia
8                Australia
9                  Austria
38  Bosnia and Herzegovina
29                  Brazil
34                Bulgaria
17                  Canada
7                    Chile
42                   China
23                 Croatia
35                  Cyprus
20          Czech Republic
43                   Egypt
26                 England
4                   France
24                 Georgia
5                  Germany
14                  Greece
13                 Hungary
33                   India
12                  Israel
0                    Italy
27                 Lebanon
22              Luxembourg
41               Macedonia
16                  Mexico
30                 Moldova
31                 Morocco
11             New Zealand
32                    Peru
1                 Portugal
15                 Romania
28                  Serbia
40                Slovakia
21                Slovenia
10            South Africa
3                    Spain
37             Switzerland
19                  Turkey
2                       US
39                 Ukraine
25                 Uruguay
18                     NaN

## sual 19

In [199]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
olke_saylari = df['country'].value_counts()
olke_saylari

US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Serbia                       12
Czech Republic               12
Macedonia                    12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Bosnia and Herzegovina        2
Armenia                       2
Slovakia                      1
China                         1
Egypt                         1
Name: country, dtype: int64

## sual 20

In [5]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
mean = df['price'].mean()
mean

35.363389129985535

In [231]:
df.price.sub(mean)

0               NaN
1        -20.363389
2        -21.363389
3        -22.363389
4         29.636611
            ...
129966    -7.363389
129967    39.636611
129968    -5.363389
129969    -3.363389
129970   -14.363389
Name: price, Length: 129971, dtype: float64

## sual 21 baxx

In [307]:
df.points.sub(df.price).max()

84.0

In [309]:
maxim = df.points.sub(df.price).max()
maxim
df2 = df.loc[(maxim),['country','price','points','description']]
df2 = pd.DataFrame(df2)
df2

                                                            84
country                                                     US
price                                                     24.0
points                                                      86
description  A healthy addition of 13% Petite Sirah provide...

In [16]:
df['points-price'] = df['points']-df['price']
maks = df['points-price'].max()
ds = df[df['points-price']==maks]['country']
ds = pd.DataFrame(ds)
ds

        country
34629  Portugal

## sual 22

In [296]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
sozler = df[df['description'].str.contains('tropical') | df['description'].str.contains('fruity') ]

len(sozler)

12487

## sual 23

In [304]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
conditions = [
    (df['country'] == 'Canada'),
    (df['points'] >= 95),
    (df['points'] <= 95) & (df['points'] >= 85)]
choices = [3, 3, 2]
df['rating'] = np.select(conditions, choices, default=1)
df

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,rating
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,2
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,2
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,2
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,2
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef),2
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation,2
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser,2
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,2
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,2

## Sual 24

In [297]:
df = pd.read_csv(r'C:\Users\Namiq\Desktop\İNNAB\Python\winemag-data-130k-v2.csv')
say = df['taster_twitter_handle'].value_counts()
say

@vossroger          25514
@wineschach         15134
@kerinokeefe        10776
@vboone              9537
@paulgwine           9532
@mattkettmann        6332
@JoeCz               5147
@wawinereport        4966
@gordone_cellars     4177
@AnneInVino          3685
@laurbuzz            1835
@suskostrzewa        1085
@worldwineguys       1005
@bkfiona               27
@winewchristina         6
Name: taster_twitter_handle, dtype: int64

## sual 25

In [305]:
df.groupby('price')[['points']].agg({'points':'max'})

        points
price
4.0         86
5.0         87
6.0         88
7.0         91
8.0         91
...        ...
1900.0      98
2000.0      97
2013.0      91
2500.0      96
3300.0      88

[390 rows x 1 columns]

## Sual 26

In [329]:
df.groupby('variety')[['price']].agg({'price':['max','min']})

             price
               max   min
variety
Abouriou      75.0  15.0
Agiorgitiko   66.0  10.0
Aglianico    180.0   6.0
Aidani        27.0  27.0
Airen         10.0   8.0
...            ...   ...
Zinfandel    100.0   5.0
Zlahtina      16.0  13.0
Zweigelt      70.0   9.0
Çalkarası     19.0  19.0
Žilavka       15.0  15.0

[707 rows x 2 columns]

## sual 27

In [331]:
df.groupby('taster_name')[['points']].agg({'points':['mean','median','max','min']})

                       points
                         mean median  max min
taster_name
Alexander Peartree  85.855422   86.0   91  80
Anna Lee C. Iijima  88.415629   88.0   98  80
Anne Krebiehl MW    90.562551   90.0   97  80
Carrie Dykes        86.395683   87.0   92  81
Christina Pickard   87.833333   88.0   93  82
Fiona Adams         86.888889   87.0   91  82
Jeff Jenssen        88.319756   89.0   97  82
Jim Gordon          88.626287   89.0   97  80
Joe Czerwinski      88.536235   89.0  100  80
Kerin O’Keefe       88.867947   89.0  100  80
Lauren Buzzeo       87.739510   88.0   95  81
Matt Kettmann       90.008686   90.0   97  81
Michael Schachner   86.907493   87.0   98  80
Mike DeSimone       89.101167   89.0   94  82
Paul Gregutt        89.082564   89.0  100  80
Roger Voss          88.708003   88.0  100  80
Sean P. Sullivan    88.755739   89.0   97  80
Susan Kostrzewa     86.609217   87.0   94  80
Virginie Boone      89.213379   90.0   99  80

## sual 28

In [362]:
df.groupby(['country','variety']).size().reset_index().rename(columns={0:'sayi'}).sort_values(['sayi'], ascending=False).head(20)

        country                   variety  sayi
1489         US                Pinot Noir  9885
1358         US        Cabernet Sauvignon  7315
1380         US                Chardonnay  6801
371      France  Bordeaux-style Red Blend  4725
814       Italy                 Red Blend  3624
1536         US                     Syrah  3244
1497         US                 Red Blend  2972
388      France                Chardonnay  2808
782       Italy                  Nebbiolo  2736
1586         US                 Zinfandel  2711
1028   Portugal            Portuguese Red  2466
1441         US                    Merlot  2311
824       Italy                Sangiovese  2265
1519         US           Sauvignon Blanc  2163
463      France                Pinot Noir  1966
475      France                      Rosé  1923
1348         US  Bordeaux-style Red Blend  1824
544     Germany                  Riesling  1790
1502         US                  Riesling  1753
24    Argentina                    Malbec  1510

## sual 29

In [366]:
df.dtypes['points']

dtype('int64')

In [367]:
df.dtypes

Unnamed: 0                 int64
country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
dtype: object

## sual 30

In [382]:
df = df.astype({"points": str}, errors = 'raise') 
df.dtypes
df3 = pd.DataFrame(df.dtypes)
df3

Unnamed: 0                 int64
country                   object
description               object
designation               object
points                    object
price                    float64
province                  object
region                    object
locale                    object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
dtype: object

## sual 31

In [381]:
dict = {'region_1': 'region', 'region_2': 'locale'}

df.rename(columns = dict, inplace = True)

df

,Unnamed: 0,country,description,designation,points,price,province,region,locale,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

## sual 32

In [389]:
df.index.name = 'wines'
df

,Unnamed: 0,country,description,designation,points,price,province,region,locale,taster_name,taster_twitter_handle,title,variety,winery
wines,,,,,,,,,,,,,,
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

## sual 33

In [394]:
data = {'a':[0,5,10,15],
        'b':[1,6,11,16],
        'c':[2,7,12,17],
        'd':[3,8,13,18],
        'e':[4,9,14,19]}

df11=pd.DataFrame(data)
df11

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [395]:
l = [{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4},
     {'a': 5, 'b': 6, 'c': 7, 'd': 8, 'e': 9},
     {'a': 10, 'b': 11, 'c': 12, 'd': 13, 'e': 14},
     {'a': 15, 'b': 16, 'c': 17, 'd': 18, 'e': 19}]

pd.DataFrame(l)

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19